# Generated by Django 4.1.3 on 2022-11-27 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_server_personas(apps, schema_editor):
    Persona = apps.get_model("Plasma", "Persona")

    Persona(
        account=apps.get_model("Plasma", "Account").objects.get(
            nuid="bfbc2.server.pc@ea.com"
        ),
        name="bfbc2.server.p",
    ).save()

    Persona(
        account=apps.get_model("Plasma", "Account").objects.get(
            nuid="bfbc.server.ps3@ea.com"
        ),
        name="bfbc.server.ps",
    ).save()

    Persona(
        account=apps.get_model("Plasma", "Account").objects.get(
            nuid="bfbc.server.xenon@ea.com"
        ),
        name="bfbc.server.xe",
    ).save()


class Migration(migrations.Migration):

    dependencies = [
        ("Plasma", "0003_serialkey"),
    ]

    operations = [
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=16, unique=True, verbose_name="Soldier Name"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Persona",
                "verbose_name_plural": "Personas",
                "ordering": ("id",),
            },
        ),
        migrations.RunPython(create_server_personas),
    ]
