THEATER_CLIENT_IP = "bfbc2-pc.theater.ea.com"
THEATER_CLIENT_PORT = 18395
THEATER_SERVER_IP = "bfbc2-pc-server.theater.ea.com"
THEATER_SERVER_PORT = 19026

MESSENGER_IP = "messaging.ea.com"
MESSENGER_PORT = 13505

CLIENT_PING_INTERVAL = 120
CLIENT_MEMCHECK_INTERVAL = 300
CLIENT_INITIAL_MEMCHECK_INTERVAL = 500
SERVER_PING_INTERVAL = 120
SERVER_MEMCHECK_INTERVAL = 300
SERVER_INITIAL_MEMCHECK_INTERVAL = 500
